channels:
  - conda-forge
dependencies:
  - python=3.5.6
  - time
  - configparser
  - mkl
  - tqdm
  - argparse
  - matplotlib
  - pandas
  - cartopy
  - numpy
  - scikit-learn
  - scipy
  - h5py
  - netCDF4
  - xarray
  - tensorflow==2.1.0
  - keras=2.3.1
  - pip=20.2.1
  - pip:
    - ruamel.yaml=0.16.10 
    - pyflann-py3
    - opencv-python 
    - itertools
    - collections
    - warnings
    - builtins
    - shapely
    - datetime
    - shutil
    - pickle
    - re
    - functools
    - traceback
    - sys
    
    
