channels:
  - menpo
  - conda-forge
  - pyviz
  - anaconda
  - defaults
dependencies:  
  - pangeo-notebook==2020.05.04
  - python
  - configparser
  - mkl
  - argparse
  - matplotlib
  - pandas
  - cartopy
  - shapely
  - numpy
  - scikit-learn
  - scipy
  - netCDF4
  - xarray
  - tensorflow==2.1.0
  - keras=2.3.1
  - pip:
    - ruamel.yaml==0.16.10 
    - opencv-python 
    - datetime
    - pickle
    - sys
    
    
