channels:
  - conda-forge
dependencies:
  - python=3.5.6
  - time
  - configparser
  - mkl
  - tqdm=4.37.0
  - argparse
  - matplotlib=3.1.3
  - pandas=1.0.3
  - cartopy=0.17.0
  - numpy=1.18.1
  - scikit-learn=0.22.2.post1
  - scipy=1.4.1
  - h5py==2.8.0
  - netCDF4=1.5.1.2
  - xarray=0.15.1
  - tensorflow==2.1.0
  - keras=2.3.1
  - pip=20.2.1
  - pip:
    - jupyterlab_launcher=0.13.1
    - jupyterlab=1.2.1
    - ipywidgets=7.4.1
    - ipykernel=4.10.0
    - nbconvert=5.5.0
    - ruamel.yaml=0.16.10 
    - pyflann-py3
    - opencv-python 
    - itertools
    - collections
    - warnings
    - builtins
    - shapely=1.7.0
    - datetime
    - shutil
    - pickle
    - re
    - functools
    - traceback
    - sys
    
    
