channels:
  - menpo
  - conda-forge
  - pyviz
  - anaconda
  - defaults
dependencies:  
  - python
  - matplotlib
  - cartopy
  - shapely
  - pandas
  - mkl
  - numpy
  - scikit-learn
  - scipy
  - netCDF4
  - xarray
  - tensorflow==1.9.0
  - keras=2.2.2
  - pip:
    - ruamel.yaml==0.16.10 
    - opencv-python
    
    
