# path files
path_files:
    domain: GULFSTREAM
#   Model file
    fileMod: ref.nc
#   OI file (list of 3 files: nadir, swot, nadir+swot)
    fileOI:  oi.nc
#   Obs file (list of 3 files: nadir, swot, nadir+swot)
    fileObs: data.nc

# data options
data_options:
    flagTrWMissingData: 2
#   load OI: work on SSH or anomaly w.r.t OI (SSH-OI)
    flagloadOIData: 1 
#   use additional covariates in initial layer
    include_covariates: True  
    lfile_cov:
    - oi.nc
    lname_cov:
    - ssh_mod
    lid_cov:
    - OI
#   Length of the 4th dimension 
    size_tw: 11
#   half-width of holes
    Wsquare: 4 
#   number of holes
    Nsquare: 3  
    sigNoise: 1e-1
    flagTrOuputWOMissingData: 1
    stdMask: 0.
    dropout: 0.0
    wl2: 0.0000
#   Index evaluation dates
    start_eval_index: 52
    end_eval_index: 94
#   Index trainig dates
    start_train_index: 122
    end_train_index: 365

# NN model options
NN_options:
#   Dimension of the latent space
    DimAE: 40    
#   model type, 1: ConvAE or 2: GENN
    flagAEType: 2     
#   multiscale model
    flag_MultiScaleAEModel: 0 

# training parameters
training_params:
#   load pre-defined AE model or not    
    batch_size: 4
    NbEpoc: 1
    Niter: 1
